RegCM_Data: /home/esp-shared-b/RegCM_Data
RegCM_Path: /home/netapp-clima/users/ggiulian/RegCM/bin
Pycordex_Path: /home/netapp-clima/users/ggiulian/RegCM/Tools/Scripts/pycordexer
RegCM_Env: /opt-ictp/ESMF/env202108
RegCM_Conf: CLM45
SLURM:
    Step: 6m
    Account: esp
    ModelPartition: esp
    ModelNodes: 5
    ModelNtasks: 20
    ModelOMP: 1
    ICBCPartition: esp
    ICBCNodes: 1
    ICBCNtasks: 20
    ICBCOMP: 20
    PostPartition: esp
    PostNodes: 1
    PostNtasks: 20
    PostOMP: 1
    Time: 24
    Mail: True
    Email: ggiulian@ictp.it
CORDEX:
    institute: ICTP
    model: RegCM
    domain: CAM-22
    global: ECMWF-ERA5
    experiment: evaluation
    ensemble: r0i0p0f0
    email: ggiulian@ictp.it
    notes: None
    regcm_release: 5
    regcm_version_id: 0
    core_srfvars: tas,pr,evspsbl,huss,hurs,ps,psl,sfcWind,uas,vas,clt,rsds,rlds
    core_stsvars: prmean,psmean,tasmean,tasmax,tasmin
    tier1_srfvars: prc,prhmax,prsn,tauu,tauv,zmla,prw,rsus,rlus,hfss,hfls,ua50m,ua100m,ua150m,va50m,va100m,va150m,ta50m,hus50m,mrros,mrro
    tier1_radvars: clwvi,clivi,rlut,rsut,rsd
    tier1_stsvars: sfcWindmax,sund
    tier1_atmvars: ua,va,ta,hus,zg,wa,mrsol,mrso,tsl
    tier2_srfvars: CAPE,CIN,LI,evspsblpot
    tier2_radvars: clh,clm,cll
    tier2_stsvars: wsgsmax
